# Generated by Django 5.1.4 on 2024-12-25 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student_DB', '0003_alter_student_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='products',
            name='name',
            field=models.CharField(default='Unnamed Product', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
