# Generated by Django 5.1.4 on 2024-12-25 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student_DB', '0004_products_image_products_name_alter_student_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='file',
        ),
        migrations.RemoveField(
            model_name='student',
            name='image',
        ),
    ]
