# Generated by Django 5.1.4 on 2024-12-25 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student_DB', '0005_remove_student_file_remove_student_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='image',
        ),
        migrations.AddField(
            model_name='products',
            name='price',
            field=models.FloatField(default=''),
        ),
    ]
