# Generated by Django 5.1.4 on 2024-12-26 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD_Operations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='family',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='family',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
